name: zwfm-liquidsoap-stereotool
services:
  liquidsoap:
    volumes:
      - ./stereotool:/stereotool
      - ./stereotool/.liquidsoap.rc:/var/cache/liquidsoap/.liquidsoap.rc
      - ./stereotool/.liquidsoap.presets:/var/cache/liquidsoap/.liquidsoap.presets
      - ./metadata/rds_rt.txt:/tmp/rds_rt.txt
    ports:
      - '0.0.0.0:8080:8080' # StereoTool GUI (TCP)
