---
name: zwfm-liquidsoap
services:
  liquidsoap:
    image: ghcr.io/oszuidwest/zwfm-liquidsoap:2.4.5-next
    container_name: liquidsoap
    volumes:
      - ./scripts:/scripts
      - ./audio:/audio
      - ./stereotool:/var/cache/liquidsoap/
      - ./socket:/tmp/liquidsoap # Server socket
      - ./hls:/hls
    environment:
      - TZ=Europe/Amsterdam
    env_file:
      - .env
    ports:
      # SRT Input 1
      - target: ${SRT_PORT_PRIMARY:-8888}
        published: ${SRT_PORT_PRIMARY:-8888}
        host_ip: ${SRT_BIND:-0.0.0.0}
        protocol: udp
      # SRT Input 2
      - target: ${SRT_PORT_SECONDARY:-9999}
        published: ${SRT_PORT_SECONDARY:-9999}
        host_ip: ${SRT_BIND:-0.0.0.0}
        protocol: udp
      # StereoTool GUI
      - target: 8080
        published: ${STEREOTOOL_WEB_PORT:-8080}
        host_ip: ${STEREOTOOL_WEB_BIND:-0.0.0.0}
        protocol: tcp
      # Stream metadata API
      - target: ${STREAM_METADATA_PORT:-7000}
        published: ${STREAM_METADATA_PORT:-7000}
        host_ip: ${STREAM_METADATA_BIND:-127.0.0.1}
        protocol: tcp
    command: /scripts/radio.liq
    restart: unless-stopped
    user: "liquidsoap:liquidsoap"
