---
name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Run all linting checks
  lint:
    uses: ./.github/workflows/lint.yml

  # Build Docker image
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Run formatting on pushes and pull requests
  format:
    needs: [lint, build]
    uses: ./.github/workflows/format.yml
    permissions:
      contents: write
