---
name: Docker Security

"on":
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  security:
    uses: oszuidwest/.github-templates/.github/workflows/docker-security-build.yml@main  # yamllint disable-line rule:line-length
    with:
      event-name: ${{ github.event_name }}
      repository-private: ${{ github.event.repository.private }}
