---
name: Format
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref_name }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install formatters
        run: |
          npm install -g prettier
          npm install -g liquidsoap-prettier
          npm install -g dclint

      - name: Format all files
        run: |
          # YAML files
          prettier --write "**/*.yml" "**/*.yaml"

          # Liquidsoap files
          liquidsoap-prettier -w "**/*.liq"

          # Docker Compose files (find all docker-compose*.yml files)
          for file in docker-compose*.yml; do
            if [ -f "$file" ]; then
              echo "Formatting $file..."
              dclint "$file" --fix
            fi
          done

      - name: Commit changes
        if: github.event_name == 'push'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            git commit -m "style: auto-format code [skip ci]"
            git push
          fi
